# Generated by Django 5.0.6 on 2025-02-28 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อสินค้า')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดสินค้า')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='ราคา')),
                ('image', models.ImageField(upload_to='products/', verbose_name='รูปสินค้า')),
            ],
        ),
    ]
