# Generated by Django 5.1 on 2025-03-01 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopdesign", "0002_order_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="payment_slip",
            field=models.ImageField(blank=True, null=True, upload_to="payment_slips/"),
        ),
        migrations.AddField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "รอยืนยัน"),
                    ("waiting_payment", "รอแอดมินตรวจสอบ"),
                    ("completed", "สำเร็จ"),
                    ("canceled", "ยกเลิก"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
