# Generated by Django 5.0.6 on 2025-03-01 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdesign', '0003_order_payment_slip_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.PositiveBigIntegerField(default=0, verbose_name='จำนวนสินค้า'),
        ),
    ]
