# Generated by Django 5.0.6 on 2025-03-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdesign', '0004_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='battery_type',
            field=models.CharField(choices=[('mf', 'ไม่เติมน้ำกลั่น'), ('hybrid', 'ไฮบริด'), ('wet', 'เติมน้ำกลั่น')], default='mf', max_length=10, verbose_name='ประเภทแบตเตอรี่'),
        ),
    ]
