# Generated by Django 5.0.6 on 2025-03-01 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdesign', '0005_product_battery_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('waiting_payment', 'รอแอดมินตรวจสอบ'), ('completed', 'สำเร็จ'), ('rejected', 'ถูกปฏิเสธ')], default='pending', max_length=20),
        ),
    ]
