# Generated by Django 5.0.6 on 2025-03-01 19:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopdesign', '0006_alter_order_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'รอยืนยัน'), ('waiting_payment', 'รอแอดมินตรวจสอบ'), ('approved', 'สลิปถูกต้อง'), ('rejected', 'สลิปไม่ถูกต้อง'), ('completed', 'สำเร็จ'), ('rejected', 'ถูกปฏิเสธ')], default='pending', max_length=20),
        ),
    ]
